#!/usr/bin/env ruby
# gem install minimagik
# Ruby script to take images from master folder and resize for Jeykll blog and place them in the images folder

files = Dir["./images_master/*.*"]

require 'mini_magick'


# Using the Date class
current_year = Time.new.year


image_path = "./images/#{current_year}"
FileUtils.mkdir_p( image_path )

# TODO skip if target already exists ?


MiniMagick2.processor = :gm
files.each do |file|
  puts file
  image = MiniMagick2::Image.open(file)
  image.resize "900"
  image.format "jpg"
 
  image_name     = File.basename(file, File.extname(file))
  new_image_name = "#{image_path}/#{image_name}.jpg"
  image.write new_image_name
end
